name: Build & deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install bundler
        run: gem install bundler
      - name: Setup bundler environment
        run: bundle install
      - name: Build site
        run: bundle exec jekyll build --source computer.mads-hartmann.com
      - name: Upload to S3
        uses: actions/aws/cli@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: computer.mads-hartmann.com
        with:
          args: s3 sync --region eu-central-1 _site/ s3://$S3_BUCKET/ --acl public-read --cache-control 'max-age=0,no-cache,no-store' --expires 'Thu, 01 Jan 1970 00:00:00 GMT'
      - name: Invalidate cache
        uses: actions/aws/cli@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
